name: Build Linux bundlers

on:
  workflow_call:

jobs:
  build-deb-package:
    name: "Build proof-producer deb package"
    runs-on: [self-hosted, Linux, X64, aws_autoscaling]
    steps:
      # https://github.com/actions/checkout/issues/1552
      - name: Clean up after previous checkout
        run: chmod +w -R ${GITHUB_WORKSPACE}; rm -rf ${GITHUB_WORKSPACE}/*;

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build proof-producer deb package
        run: |
          nix bundle --bundler . .#proof-producer
          ls -l ./deb-package-proof-producer/proof-producer_*_amd64.deb

      - name: Build proof-producer-benchmarks deb package
        run: |
          nix bundle --bundler .#deb-benchmarks .#proof-producer
          ls -l ./deb-package-proof-producer-benchmarks/proof-producer-benchmarks_*_amd64.deb

      - name: upload packages to s3
        if: (github.event_name == 'push' && github.ref == 'refs/heads/master') || github.event_name == 'workflow_dispatch'
        env:
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        run: |
          export PATH=/home/ec2-user/.local/bin:${PATH}
          sudo yum update -y
          sudo yum install -y awscli python3-pip
          pip3 install -U mkrepo
          aws s3 cp "deb-package-proof-producer/`ls deb-package-proof-producer`" s3://nil-deb-repo/ubuntu/pool/main/p/proof-producer/
          aws s3 cp "deb-package-proof-producer-benchmarks/`ls deb-package-proof-producer-benchmarks`" s3://nil-deb-repo/ubuntu/pool/main/p/proof-producer-benchmarks/
          mkrepo s3://nil-deb-repo/ubuntu
