name: PR Testing

on:
  pull_request:
  merge_group:
  push:
    branches:
      - master

jobs:
  test-linux-gcc:
    name: Linux placeholder testing with gcc
    uses: ./.github/workflows/gcc-linux-nix-check.yml
    if: |
      always() && !cancelled()
    secrets: inherit

  test-linux-clang:
    name: Linux placeholder testing with clang
    uses: ./.github/workflows/clang-linux-nix-check.yml
    if: |
      always() && !cancelled()
    secrets: inherit

  check-proof-producer:
    name: Check Proof Producer
    uses: ./.github/workflows/check-proof-producer.yml
    if: |
      always() && !cancelled()
    secrets: inherit

  verify-circuit-proof:
    name: Verify Circuit Proof
    uses: ./.github/workflows/verify-circuit-proof.yml
    if: |
      always() && !cancelled()
    secrets: inherit
